// src/admin/AdminRecent.tsx
import { useCallback, useEffect, useState } from 'react';

import { fmtAgo, PosterThumb } from '@/lib';
import { adminApiBase, type RecentItem } from './services';

export function AdminRecent() {
  const api = adminApiBase();
  const [items, setItems] = useState<RecentItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [pending, setPending] = useState<number | null>(null);

  const loadRecent = useCallback(async () => {
    try {
      const response = await fetch(`${api}/recent`);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const body = await response.json();
      setItems(Array.isArray(body) ? body : []);
      setError('');
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, [api]);

  useEffect(() => {
    void loadRecent();
    const timer = setInterval(() => void loadRecent(), 15000);
    return () => clearInterval(timer);
  }, [loadRecent]);

  const requeue = async (index: number) => {
    setPending(index);
    try {
      const response = await fetch(`${api}/recent/${index}/queue`, { method: 'POST' });
      const payload: { error?: string; first_title?: string } = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload.error || `HTTP ${response.status}`);
      notify(`Requeued: ${payload.first_title || titleOf(items[index] ?? {})}`);
      await window.jetstreamQueue?.reload?.();
    } catch (err) {
      notify(`Requeue failed: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setPending(null);
    }
  };

  return (
    <section id="recent-panel">
      <div className="head">
        <div>
          <h2>Recently played</h2>
          <span className="recent-subtitle">{items.length ? `${items.length} saved` : 'Nothing yet'}</span>
        </div>
        <button type="button" onClick={loadRecent} title="Refresh recently played">Refresh</button>
      </div>
      <ul id="recent-list" aria-busy={loading}>
        {loading ? <li className="recent-state">Loading recently played...</li> :
          error ? <li className="recent-state error-state"><span>Failed to load: {error}</span><button type="button" onClick={loadRecent}>Retry</button></li> :
            !items.length ? <li className="recent-state"><strong>No recently played items</strong><span>Played files and URLs will show up here for quick requeue.</span></li> :
              items.slice(0, 8).map((item, index) => {
                const source = item.source || {};
                return (
                  <li className="recent-row" key={`${source.ref ?? ''}:${item.ts ?? ''}:${index}`}>
                    <span className="recent-thumb">{source.type === 'file' && source.ref ? <PosterThumb src={`/poster?path=${encodeURIComponent(source.ref)}`} /> : <span aria-hidden="true">U</span>}</span>
                    <span className="recent-main">
                      <span className="recent-title" title={source.ref}>{titleOf(item)}</span>
                      <span className="recent-meta">
                        <span>{sourceOf(item)}</span>
                        {source.duration ? <span>{fmtDur(source.duration)}</span> : null}
                        <span>{item.ts ? fmtAgo(Math.max(0, Math.floor(Date.now() / 1000 - item.ts))) : ''}</span>
                      </span>
                    </span>
                    <button type="button" onClick={() => requeue(index)} disabled={pending === index} title={`Requeue ${titleOf(item)}`}>{pending === index ? 'Adding...' : 'Requeue'}</button>
                  </li>
                );
              })}
      </ul>
    </section>
  );
}

function titleOf(item: RecentItem): string {
  const source = item.source || {};
  return source.title || source.ref || 'Untitled';
}

function sourceOf(item: RecentItem): string {
  const source = item.source || {};
  if (source.type === 'file') return 'File';
  if (source.type === 'url') return source.is_live ? 'Live URL' : 'URL';
  return 'Source';
}

function fmtDur(sec: number | null | undefined): string {
  if (!sec || !Number.isFinite(sec) || sec < 0) return '';
  const t = Math.floor(sec);
  const h = Math.floor(t / 3600);
  const m = Math.floor((t % 3600) / 60);
  const s = t % 60;
  const pad = (n: number) => String(n).padStart(2, '0');
  return h ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

function notify(message: string): void {
  (window.jetstreamShowToast || window.showToast)?.(message);
}

// src/admin/AdminRecent.svelte
<script>
  import { onMount } from "svelte";

  const api = location.pathname.startsWith("/controls") ? "/api/control" : "/admin/api";

  let items = [];
  let loading = true;
  let error = "";
  let pending = null;

  function toast(message) {
    if (typeof window.jetstreamShowToast === "function") window.jetstreamShowToast(message);
  }

  function titleOf(item) {
    const source = item.source || {};
    return source.title || source.ref || "Untitled";
  }

  function sourceOf(item) {
    const source = item.source || {};
    if (source.type === "file") return "File";
    if (source.type === "url") return source.is_live ? "Live URL" : "URL";
    return "Source";
  }

  function timeAgo(ts) {
    if (!ts) return "";
    const delta = Math.max(0, Math.floor(Date.now() / 1000 - ts));
    if (delta < 60) return `${delta}s ago`;
    if (delta < 3600) return `${Math.floor(delta / 60)}m ago`;
    if (delta < 86400) return `${Math.floor(delta / 3600)}h ago`;
    return `${Math.floor(delta / 86400)}d ago`;
  }

  function fmtDur(sec) {
    if (!sec || !Number.isFinite(sec) || sec < 0) return "";
    sec = Math.floor(sec);
    const h = Math.floor(sec / 3600);
    const m = Math.floor((sec % 3600) / 60);
    const s = sec % 60;
    const pad = (n) => String(n).padStart(2, "0");
    return h ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
  }

  async function loadRecent() {
    try {
      const response = await fetch(`${api}/recent`);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      items = await response.json();
      error = "";
    } catch (err) {
      error = err.message;
    } finally {
      loading = false;
    }
  }

  async function requeue(index) {
    pending = index;
    try {
      const response = await fetch(`${api}/recent/${index}/queue`, { method: "POST" });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(payload.error || `HTTP ${response.status}`);
      toast(`Requeued: ${payload.first_title || titleOf(items[index])}`);
      if (window.jetstreamQueue?.reload) await window.jetstreamQueue.reload();
    } catch (err) {
      toast(`Requeue failed: ${err.message}`);
    } finally {
      pending = null;
    }
  }

  onMount(() => {
    loadRecent();
    const timer = setInterval(loadRecent, 15000);
    return () => clearInterval(timer);
  });
</script>

<section id="recent-panel">
  <div class="head">
    <div>
      <h2>Recently played</h2>
      <span class="recent-subtitle">{items.length ? `${items.length} saved` : "Nothing yet"}</span>
    </div>
    <button type="button" on:click={loadRecent} title="Refresh recently played">Refresh</button>
  </div>

  <ul id="recent-list" aria-busy={loading}>
    {#if loading}
      <li class="recent-state">Loading recently played...</li>
    {:else if error}
      <li class="recent-state error-state">
        <span>Failed to load: {error}</span>
        <button type="button" on:click={loadRecent}>Retry</button>
      </li>
    {:else if !items.length}
      <li class="recent-state">
        <strong>No recently played items</strong>
        <span>Played files and URLs will show up here for quick requeue.</span>
      </li>
    {:else}
      {#each items.slice(0, 8) as item, index}
        {@const source = item.source || {}}
        <li class="recent-row">
          <span class="recent-thumb">
            {#if source.type === "file" && source.ref}
              <img loading="lazy" alt="" src={`/poster?path=${encodeURIComponent(source.ref)}`}>
            {:else}
              <span aria-hidden="true">U</span>
            {/if}
          </span>
          <span class="recent-main">
            <span class="recent-title" title={source.ref}>{titleOf(item)}</span>
            <span class="recent-meta">
              <span>{sourceOf(item)}</span>
              {#if source.duration}<span>{fmtDur(source.duration)}</span>{/if}
              <span>{timeAgo(item.ts)}</span>
            </span>
          </span>
          <button type="button" on:click={() => requeue(index)} disabled={pending === index} title={`Requeue ${titleOf(item)}`}>
            {pending === index ? "Adding..." : "Requeue"}
          </button>
        </li>
      {/each}
    {/if}
  </ul>
</section>
