// src/viewer/requests-panel.tsx
import { useCallback } from 'react';

import {
  IslandProps,
  clientSid,
  useActions,
  useCollapse,
  useHostClass,
  usePolled,
  usePublishRefresh,
} from '@/lib';

import { MediaRequest, RequestFeed, approve, deny, listRequests, vote } from './requests';

const EMPTY: RequestFeed = { requests: [], can_manage: false };

/** Mounts into the page's <section id="reqlist-panel" jet-requests-panel>. */
export function RequestsPanel({ host }: IslandProps) {
  const act = useActions();
  const fetcher = useCallback(() => listRequests(clientSid()), []);
  const { data: feed, refresh } = usePolled(fetcher, { initial: EMPTY });
  const [collapsed, setCollapsed] = useCollapse('jetstream_reqlist_collapsed');
  useHostClass(host, 'collapsed', collapsed);

  // The library panel calls this after filing a request, so the new entry (or
  // its bumped vote count) shows up without waiting for the tick.
  usePublishRefresh('requests', useCallback(() => void refresh(), [refresh]));

  const onVote = async (r: MediaRequest) => {
    // Deliberately quiet: voting is high-frequency and its result is visible in
    // the count, so a toast per click would be noise.
    await act.run(`vote:${r.id}`, () => vote(r.id, clientSid()), { ok: '', fail: 'Vote failed' });
    void refresh();
  };
  const onApprove = async (r: MediaRequest) => {
    await act.run(`approve:${r.id}`, () => approve(r.id), { ok: 'Queued', fail: 'Approve failed' });
    void refresh();
    // Approving moves the item into the queue, which is a separate island.
    window.jetstream?.['queue']?.();
  };
  const onDeny = async (r: MediaRequest) => {
    await act.run(`deny:${r.id}`, () => deny(r.id), { ok: 'Request removed', fail: 'Deny failed' });
    void refresh();
  };

  const n = feed.requests.length;
  return (
    <>
      {/* A button, like #queue-head: the header is an interactive control, so a
          div leaves it unreachable by keyboard. viewer.css carries the chrome
          opt-out and the :focus-visible ring for this id. */}
      <button
        id="reqlist-head"
        type="button"
        aria-expanded={!collapsed}
        aria-controls="reqlist"
        onClick={() => setCollapsed(!collapsed)}
      >
        <span className="rh-label">requests</span>
        <span id="reqlist-count">{n ? `${n} ${n === 1 ? 'request' : 'requests'}` : ''}</span>
        <span className="toggle" aria-hidden="true">{collapsed ? '▸' : '▾'}</span>
      </button>

      <ul id="reqlist">
        {n === 0 && (
          <li className="empty">No requests yet — find something in the library below and tap Request.</li>
        )}
        {feed.requests.map((r) => (
          <li key={r.id}>
            <button
              type="button"
              className={'req-vote' + (r.voted ? ' voted' : '')}
              title={r.voted ? 'Remove your vote' : 'Vote for this'}
              disabled={act.busy(`vote:${r.id}`)}
              onClick={() => void onVote(r)}
            >
              <span className="req-arrow">▲</span>
              <span className="req-n">{r.votes}</span>
            </button>

            <div className="req-meta">
              <div className="req-title">{r.title || '(untitled)'}</div>
              {r.requester && <div className="req-by">by {r.requester}</div>}
            </div>

            {feed.can_manage && (
              <div className="req-actions">
                <button type="button" className="req-ok" title="Approve & queue"
                        disabled={act.busy(`approve:${r.id}`)} onClick={() => void onApprove(r)}>
                  Queue
                </button>
                <button type="button" className="req-no" title="Deny"
                        disabled={act.busy(`deny:${r.id}`)} onClick={() => void onDeny(r)}>
                  ✕
                </button>
              </div>
            )}
          </li>
        ))}
      </ul>
    </>
  );
}

// src/viewer-app/requests-panel.component.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';

import { actions, clientSid, collapseState, polled, publishRefresh } from '@jet/ui';

import { MediaRequest, RequestFeed, RequestsService } from './requests.service';

@Component({
  // Adopts the page's existing <section id="reqlist-panel">, so every rule in
  // viewer.css and the theme keeps matching.
  selector: '[jet-requests-panel]',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class.collapsed]': 'collapsed()',
  },
  template: `
    <!-- A button, like #queue-head: the header is an interactive control, so a
         div leaves it unreachable by keyboard. viewer.css already carries the
         chrome opt-out (border/font/appearance) and the :focus-visible ring for
         this id, and the label is .rh-label there rather than h2 — an <h2> here
         matches neither that rule nor the theme's uppercase treatment. -->
    <button
      id="reqlist-head"
      type="button"
      [attr.aria-expanded]="!collapsed()"
      aria-controls="reqlist"
      (click)="collapsed.set(!collapsed())"
    >
      <span class="rh-label">requests</span>
      <span id="reqlist-count">{{ countLabel() }}</span>
      <span class="toggle" aria-hidden="true">{{ collapsed() ? '▸' : '▾' }}</span>
    </button>

    <ul id="reqlist">
      @for (r of requests(); track r.id) {
        <li>
          <button
            type="button"
            class="req-vote"
            [class.voted]="r.voted"
            [title]="r.voted ? 'Remove your vote' : 'Vote for this'"
            [disabled]="act.busy('vote:' + r.id)"
            (click)="vote(r)"
          >
            <span class="req-arrow">▲</span>
            <span class="req-n">{{ r.votes }}</span>
          </button>

          <div class="req-meta">
            <div class="req-title">{{ r.title || '(untitled)' }}</div>
            @if (r.requester) {
              <div class="req-by">by {{ r.requester }}</div>
            }
          </div>

          @if (canManage()) {
            <div class="req-actions">
              <button
                type="button"
                class="req-ok"
                title="Approve &amp; queue"
                [disabled]="act.busy('approve:' + r.id)"
                (click)="approve(r)"
              >
                Queue
              </button>
              <button
                type="button"
                class="req-no"
                title="Deny"
                [disabled]="act.busy('deny:' + r.id)"
                (click)="deny(r)"
              >
                ✕
              </button>
            </div>
          }
        </li>
      } @empty {
        <li class="empty">
          No requests yet — find something in the library below and tap Request.
        </li>
      }
    </ul>
  `,
})
export class RequestsPanelComponent {
  private readonly api = inject(RequestsService);
  protected readonly act = actions();

  private readonly poll = polled(() => this.api.list(clientSid()), {
    initial: { requests: [], can_manage: false } as RequestFeed,
  });

  readonly requests = computed(() => this.poll.value().requests);
  readonly canManage = computed(() => this.poll.value().can_manage);

  readonly collapsed = collapseState('jetstream_reqlist_collapsed');

  constructor() {
    // The library-search panel calls this after filing a request, so the new
    // entry (or its bumped vote count) shows up without waiting for the tick.
    publishRefresh('requests', () => this.poll.refresh());
  }

  countLabel(): string {
    const n = this.requests().length;
    return n ? `${n} ${n === 1 ? 'request' : 'requests'}` : '';
  }

  async vote(r: MediaRequest): Promise<void> {
    // Deliberately quiet: voting is high-frequency and its result is visible in
    // the count, so a toast per click would be noise.
    await this.act.run(`vote:${r.id}`, () => this.api.vote(r.id, clientSid()), {
      ok: '',
      fail: 'Vote failed',
    });
    this.poll.refresh();
  }

  async approve(r: MediaRequest): Promise<void> {
    await this.act.run(`approve:${r.id}`, () => this.api.approve(r.id), {
      ok: 'Queued',
      fail: 'Approve failed',
    });
    this.poll.refresh();
    // Approving moves the item into the queue, which is a separate component.
    window.jetstream?.['queue']?.();
  }

  async deny(r: MediaRequest): Promise<void> {
    await this.act.run(`deny:${r.id}`, () => this.api.deny(r.id), {
      ok: 'Request removed',
      fail: 'Deny failed',
    });
    this.poll.refresh();
  }
}
